### ISSUE TITLE
it doesn't work at vue。

### ISSUE THREAD

**Issue by X-Mars** [grassator/insert-text-at-cursor#1]
main.js
`
import insertTextAtCursor from 'insert-text-at-cursor';
Vue.use(insertTextAtCursor);
`
Chrome Console：
`
index.js?585e:26 Uncaught TypeError: input.focus is not a function
`
Thinks

**Comment by andrerpena** [comment]
@X-Mars Isn't `Vue.use` supposed to be used with a Vue.js plugin? This library expects an `input` or `textarea` as first parameter

**Comment by X-Mars** [comment]
@andrerpena 
 thanks my brother。
 got it.
