### ISSUE TITLE
Event.initEvent() deprecated.

### ISSUE THREAD

**Issue by kmvan** [grassator/insert-text-at-cursor#17]
Deprecated: https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent

Use `Event()`: https://developer.mozilla.org/en-US/docs/Web/API/Event/Event

**Comment by grassator** [comment]
I would be open to consider an outside PR to change, however there is currently no automated infrastructure to test that this does not break code so even verifying the change is a big task.

My main question is if this deprecated usage is *actually* causing a problem vs it something that is *nice to do*. I highly doubt that `initEvent` support will be dropped any time soon as so many older (and even newer) websites rely on it to function.

**Comment by kmvan** [comment]
Compatibility with older browsers is also a big deal.
Thanks anyway for your project.
