### ISSUE TITLE
Exclude index.js from published library

### ISSUE THREAD

**Issue by lukezavrel** [grassator/insert-text-at-cursor#4]
Hello,
I am using react-mde library, which has dependency to this library in the latest version.
After updating react-mde, webpack throws error during build
```
ERROR in assets/js/bundle.js?v=8c4ec7c34d426ef93de7 from UglifyJs
Unexpected token: name (browserSupportsTextareaTextNodes)
```
This is caused by webpack prioritizing `module` field over `main` field by default and UglifyJs can't read ES6 syntax that is in `index.js`.  
Would it be possible to add `.npmignore` file with `index.js` in it so webpack uses the correct path?
Thanks.

**Comment by stof** [comment]
An option here would be to add a new build output in the rollup config, to output a ES module, but still processed with babel.

@lukezavrel what you can do in the meantime is to apply babel on files from this module in your webpack config.
